input {
  tcp {
    port => 5001
    codec => json_lines
  }
}
filter {
  # Add filters (geoip, mutate, etc.) if you want
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "honeypot-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
